apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
  labels:
    app.kubernetes.io/name: python-service
    app.kubernetes.io/version: b692b1813afb433358de7c6bc7f4bc584b990160
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: python-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-service
        app.kubernetes.io/version: b692b1813afb433358de7c6bc7f4bc584b990160
    spec:
      containers:
        - name: python-service
          image: ghcr.io/aisrael/python-service:b692b1813afb433358de7c6bc7f4bc584b990160
          ports:
            - containerPort: 8000
