apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
  labels:
    app.kubernetes.io/name: python-service
    app.kubernetes.io/version: 7a4b9cd56352f39286b30e2ec224e9ae831ab5ef
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: python-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-service
        app.kubernetes.io/version: 7a4b9cd56352f39286b30e2ec224e9ae831ab5ef
    spec:
      containers:
        - name: python-service
          image: ghcr.io/aisrael/python-service:7a4b9cd56352f39286b30e2ec224e9ae831ab5ef
          ports:
            - containerPort: 8000
