apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
  labels:
    app.kubernetes.io/name: python-service
    app.kubernetes.io/version: f02827276c080b8ebd0d73e89b4b254a1e21d67f
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: python-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-service
        app.kubernetes.io/version: f02827276c080b8ebd0d73e89b4b254a1e21d67f
    spec:
      containers:
        - name: python-service
          image: ghcr.io/aisrael/python-service:f02827276c080b8ebd0d73e89b4b254a1e21d67f
          ports:
            - containerPort: 8000
