apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
  labels:
    app.kubernetes.io/name: python-service
    app.kubernetes.io/version: bd9893943a3d09c5484dc3e934a1bd3ea3533ac4
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: python-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-service
        app.kubernetes.io/version: bd9893943a3d09c5484dc3e934a1bd3ea3533ac4
    spec:
      containers:
        - name: python-service
          image: ghcr.io/aisrael/python-service:bd9893943a3d09c5484dc3e934a1bd3ea3533ac4
          ports:
            - containerPort: 8000
