apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
  labels:
    app.kubernetes.io/name: python-service
    app.kubernetes.io/version: 903d20b255093c1ce70e28bea66d7e2166802893
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: python-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-service
        app.kubernetes.io/version: 903d20b255093c1ce70e28bea66d7e2166802893
    spec:
      containers:
        - name: python-service
          image: ghcr.io/aisrael/python-service:903d20b255093c1ce70e28bea66d7e2166802893
          ports:
            - containerPort: 8000
