kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: minikube-cluster
  namespace: argocd
spec:
  source:
    repoURL: "https://github.com/aisrael/softcon2022.git"
    path: clusters/development/minikube
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: argocd
  syncPolicy:
    automated: {}
